#!/bin/sh

#rm -rf m4ri-20140914
#tar zxvf m4ri-20140914.tar.gz
#cd m4ri-20140914
#./configure && make

cd ../mini-init-lib
make clean
CFLAGS="-I. -I../maplecomsps_lrb_vsids_18/MapleCOMSPS_LRB_VSIDS_2/" make

cd ../maplecomsps_lrb_vsids_18/MapleCOMSPS_LRB_VSIDS_2/simp
MROOT=.. make clean rs
cp -f ./minisat_static ../../bin/MapleCOMSPS_LRB_VSIDS_2
